CREATE DATABASE BIBLIOTECA

USE BIBLIOTECA

DROP DATABASE BIBLIOTECA

SELECT * FROM AUTORES
SELECT * FROM EMAIL
SELECT * FROM LIVROS
SELECT * FROM EDITORAS

SELECT A.NOME, E.CODEMA, E.EMAIL, E.FK_COD_AUT FROM AUTORES A
INNER JOIN EMAIL E
ON A.CODAUT = E.FK_COD_AUT
